---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-lv-claim
  annotations:
    volume.beta.kubernetes.io/storage-class: "ibmc-file-retain-silver"
  labels:
    billingType: "hourly"
    app: wordpress
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wp-lv-claim
  annotations:
    volume.beta.kubernetes.io/storage-class: "ibmc-file-retain-silver"
  labels:
    billingType: "hourly"
    app: wordpress
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
